services:
  - type: web
    name: shelfserve-api
    runtime: node
    plan: free
    buildCommand: cd src && npm install && npx prisma generate --schema=../prisma/schema.prisma
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_PATH
        value: /opt/render/project/node_modules
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d

databases:
  - name: postgres
    plan: free
