openapi: 3.1.0
info:
  title: ShelfServe API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://shelfserve-lib-api.onrender.com/shelfserve-docs
    description: Production development server
tags:
  - name: users
    description: User-related endpoints
paths:
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/userId.yaml
  /users/{id}/role:
    $ref: paths/userIdRole.yaml
  /books:
    $ref: paths/books.yaml
  /books/{id}:
    $ref: paths/bookId.yaml
  /authors:
    $ref: paths/authors.yaml
  /authors{id}:
    $ref: paths/authorId.yaml
  /genres:
    $ref: paths/genres.yaml
  /genres/{id}:
    $ref: paths/genreId.yaml
